### ISSUE TITLE
Bug? Behavior if a not supported lang is passed in url

### ISSUE THREAD

**Issue by barrynorman** [stokito/grails-locale-configuration-plugin#11]
Supported langs = [de, en]
Default lang = en

My accept header: de, en
1. First access is right --> lang is de
2. Switching lang via selector works
3. Pass lang param (e.g. lang=es) --> es is not supported --> locale is en but should be de, because my accept lang header is de, en

I would expect de because of the order and priority

**Comment by stokito** [comment]
Actually it's a feature, but you right, a bad design.
It happens because lang param is hooked by LocaleChangeInterceptor that just call setLocale() on resolver.
Original method setLocale() from SessionLocaleResolver just stores locale from lang param to session.
And then, every time resolveLocale() will return that stored locale from session.

So, current implementation of setLocale() don't used request.locales.
I'll fix it right now

**Comment by stokito** [comment]
Fixed in 0.4 release
